In [1]:
using LinearAlgebra

In [2]:
A = [2 5
1 2]

2×2 Matrix{Int64}:
 2  5
 1  2

In [3]:
B = [21
8]

2-element Vector{Int64}:
 21
  8

In [7]:
F = lu(A)

LU{Float64, Matrix{Float64}}
L factor:
2×2 Matrix{Float64}:
 1.0  0.0
 0.5  1.0
U factor:
2×2 Matrix{Float64}:
 2.0   5.0
 0.0  -0.5

In [9]:
x = A\B

2-element Vector{Float64}:
 -2.0
  5.0

In [10]:
using Plots

In [11]:
using Random

In [16]:
phi = pi/7
a = 2 
b = 11.5
x_0 = 3
y_0 = -1

fx(t) = a*cos(phi)*cos(t) - b*sin(phi)*sin(t) + x_0
fy(t) = a*sin(phi)*sin(t) + b*cos(phi)*cos(t) + x_0

N = 10
ts = LinRange(0, 2*pi, N)
x = fx.(ts)
y = fy.(ts)

10-element Vector{Float64}:
 13.36114198087782
 11.494885421916681
  5.653777563905558
 -1.4290623097093365
 -6.439494705066647
 -7.033082619625306
 -2.932079671168485
  3.9446092831499633
 10.379305055719744
 13.36114198087782

In [17]:
plot(x,y, seriestype =:scatter, label = "Observations", legend =:topleft)
plot!(fx.(ts), fy.(ts), linewidth = 10, label = "True Elipse")

LoadError: UndefVarError: plot not defined

In [18]:
x = fx.(ts) + randn(N)*0.1
Y = fY.(ts) + randn(N)*0.1

LoadError: UndefVarError: fY not defined

In [ ]:
plot(x,y, seriestype =:scatter, label = "Observations", legend =:topleft)
plot!(fx.(ts), fy.(ts), linewidth = 10, label = "True Elipse")

In [ ]:
A = [x.^2 y.^2 x.*y x y]
b = ones(N)
p = A\b

In [10]:
X = LinRange(minimum(x), maximum(x), N)



LoadError: UndefVarError: x not defined

In [11]:
Y = LinRange(minimum(x), maximum(x), N)

LoadError: UndefVarError: x not defined

In [12]:

F = Array{Float64}(undef,N,N)

LoadError: UndefVarError: N not defined

In [14]:
for i in 1:N
    for j in 1:N
        F[i,j] = p[1]*X[i]^2 + p[2]*Y[j]^2 + p[3]*X[i]*Y[j] + p[4]*X[i] + p[5]*Y[j]
    end
end


LoadError: UndefVarError: N not defined